import type { ProviderConfig } from "@/types/provider";

export const PROVIDER_REGISTRY: Record<string, ProviderConfig> = {
  // --- Provedores Oficiais & Cloud Empresariais ---
  openai: {
    id: "openai",
    name: "OpenAI Oficial",
    baseUrl: "https://api.openai.com/v1",
    authType: "bearer",
    models: [
      "gpt-4o",
      "gpt-4o-mini",
      "o1",
      "o1-mini",
      "o3-mini",
      "chatgpt-4o-latest",
      "gpt-4-turbo",
    ],
    freeTier: false,
    costPerMillionInput: 2.5,
    costPerMillionOutput: 10.0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  azure: {
    id: "azure",
    name: "Azure OpenAI Service",
    baseUrl: "https://openai.azure.com",
    authType: "apikey-header",
    headerName: "api-key",
    models: ["azure/gpt-4o", "azure/gpt-4o-mini"],
    freeTier: false,
    costPerMillionInput: 2.5,
    costPerMillionOutput: 10.0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  bedrock: {
    id: "bedrock",
    name: "Amazon Bedrock",
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
    authType: "bearer",
    models: [
      "anthropic.claude-3-5-sonnet-20241022-v2:0",
      "meta.llama3-70b-instruct-v1:0",
    ],
    freeTier: false,
    costPerMillionInput: 3.0,
    costPerMillionOutput: 15.0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  alibaba: {
    id: "alibaba",
    name: "Alibaba Cloud (DashScope / Qwen)",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    authType: "bearer",
    models: [
      "qwen-max",
      "qwen-plus",
      "qwen-turbo",
      "qwen2.5-coder-32b-instruct",
      "qwen2.5-72b-instruct",
    ],
    freeTier: true,
    costPerMillionInput: 0.2,
    costPerMillionOutput: 0.6,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },

  // --- Provedores Gratuitos de Alta Capacidade & Agregadores ---
  gemini: {
    id: "gemini",
    name: "Google Gemini (AI Studio)",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    authType: "query",
    models: ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-flash", "gemini-2.5-pro"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    rpmLimit: 15,
  },
  antigravity: {
    id: "antigravity",
    name: "Antigravity CLI (Google Cloud Code Assist)",
    baseUrl: "https://cloudcode-pa.googleapis.com",
    authType: "oauth",
    models: ["gemini-2.5-pro", "gemini-2.5-flash", "claude-3-7-sonnet"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  groq: {
    id: "groq",
    name: "Groq Cloud",
    baseUrl: "https://api.groq.com/openai/v1",
    authType: "bearer",
    // A Groq descontinuou llama-3.3/llama-3.1 e hoje expoe os ids com namespace,
    // por exemplo "openai/gpt-oss-120b". O id SEM namespace e recusado com 404.
    models: ["openai/gpt-oss-120b", "openai/gpt-oss-20b"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
    rpmLimit: 30,
  },
  cerebras: {
    id: "cerebras",
    name: "Cerebras Inference",
    baseUrl: "https://api.cerebras.ai/v1",
    authType: "bearer",
    // Cerebras hoje expoe gpt-oss-120b e qwen-3.8-27b (ambos exigem plano pago);
    // llama3.3-70b e llama3.1-8b retornam 404 para contas novas.
    models: ["gpt-oss-120b", "qwen-3.8-27b", "llama3.3-70b", "llama3.1-8b"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
    rpmLimit: 30,
  },
  "cloudflare-ai": {
    id: "cloudflare-ai",
    name: "Cloudflare Workers AI (Nativo)",
    authType: "native-binding",
    models: [
      "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
      "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
      "@cf/qwen/qwen2.5-coder-32b-instruct",
      "@cf/meta/llama-3.2-3b-instruct",
    ],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: false,
    supportsVision: false,
  },
  // 1min.ai foi removido do catálogo nativo.
  // Cadastre-o como provedor customizado no painel admin com:
  //   baseUrl: https://1min--com-tool.samuca.workers.dev/v1  (ou outro endpoint compatível com OpenAI)
  //   protocol: openai
  // O sistema roteia automaticamente para qualquer endpoint OpenAI/Anthropic-compatible.
  freeapikey: {
    id: "freeapikey",
    name: "FreeAPIKey (Agregador)",
    baseUrl: "https://api.freeapikey.com/v1",
    authType: "bearer",
    models: ["gpt-4o-mini", "claude-3-haiku", "gemini-flash"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: false,
    supportsVision: false,
  },
  pollinations: {
    id: "pollinations",
    name: "Pollinations.ai (Ilimitado / Keyless)",
    baseUrl: "https://gen.pollinations.ai/v1",
    authType: "bearer",
    // Alias gratuito atual e modelos de texto retornados pelo catalogo oficial.
    models: ["openai", "deepseek/deepseek-v4.1-flash", "qwen/qwen3.8-flash", "openai/gpt-oss-20b"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: false,
    supportsVision: false,
  },
  openrouter: {
    id: "openrouter",
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    authType: "bearer",
    models: [
      "meta-llama/llama-3.3-70b-instruct:free",
      "deepseek/deepseek-r1:free",
      "google/gemini-2.0-flash-exp:free",
    ],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  sambanova: {
    id: "sambanova",
    name: "SambaNova Systems",
    baseUrl: "https://api.sambanova.ai/v1",
    authType: "bearer",
    models: ["Meta-Llama-3.3-70B-Instruct", "Qwen2.5-72B-Instruct"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
  },
  mistral: {
    id: "mistral",
    name: "Mistral AI",
    baseUrl: "https://api.mistral.ai/v1",
    authType: "bearer",
    models: ["mistral-small-latest", "codestral-latest"],
    freeTier: true,
    costPerMillionInput: 0.2,
    costPerMillionOutput: 0.6,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
  },
  deepseek: {
    id: "deepseek",
    name: "DeepSeek API",
    baseUrl: "https://api.deepseek.com/v1",
    authType: "bearer",
    models: ["deepseek-chat", "deepseek-reasoner", "deepseek-flash", "deepseek-v4-pro"],
    freeTier: false,
    costPerMillionInput: 0.14,
    costPerMillionOutput: 0.28,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
  },
  cheaperinference: {
    id: "cheaperinference",
    name: "CheaperInference",
    baseUrl: "https://api.cheaperinference.com/v1",
    authType: "bearer",
    models: [],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  agentrouter: {
    id: "agentrouter",
    name: "AgentRouter",
    baseUrl: "https://api.agentrouter.org/v1",
    authType: "bearer",
    models: [],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  bazaarlink: {
    id: "bazaarlink",
    name: "BazaarLink",
    baseUrl: "https://api.bazaarlink.ai/v1",
    authType: "bearer",
    models: [],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  huggingface: {
    id: "huggingface",
    name: "Hugging Face (Serverless)",
    baseUrl: "https://api-inference.huggingface.co/v1",
    authType: "bearer",
    models: [],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: false,
    supportsVision: false,
  },
  nvidia: {
    id: "nvidia",
    name: "Nvidia NIM",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    authType: "bearer",
    models: [],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
};



// Registry mutável para provedores customizados registrados via painel admin
export const CUSTOM_PROVIDER_REGISTRY: Record<string, ProviderConfig> = {};

export function registerCustomProvider(id: string, cfg: Partial<ProviderConfig> & { baseUrl: string }): void {
  CUSTOM_PROVIDER_REGISTRY[id] = {
    id,
    name: cfg.name || id,
    baseUrl: cfg.baseUrl,
    authType: cfg.authType || "bearer",
    headerName: cfg.headerName,
    models: cfg.models || [],
    freeTier: cfg.freeTier ?? true,
    costPerMillionInput: cfg.costPerMillionInput ?? 0,
    costPerMillionOutput: cfg.costPerMillionOutput ?? 0,
    supportsStreaming: cfg.supportsStreaming ?? true,
    supportsTools: cfg.supportsTools ?? true,
    supportsVision: cfg.supportsVision ?? false,
  } as ProviderConfig;
}

export function getProviderConfig(id: string): ProviderConfig | undefined {
  return PROVIDER_REGISTRY[id] || CUSTOM_PROVIDER_REGISTRY[id];
}
